FROM python:3.12
RUN pip install poetry
LABEL MAINTAINER="abc@gmail.com"

WORKDIR /code

ADD ./pyproject.toml /code/
ADD ./helloworld /code/helloworld/  

RUN poetry install
CMD  [ "poetry" , "run" , "uvicorn", "helloworld.main:app" , "--host" , "0.0.0.0" ]






